import jsPDF from "jspdf";

export const generateInvoice = (order: any, role: "buyer" | "seller") => {
  const doc = new jsPDF();

  const formatRupiah = (num: number) =>
    new Intl.NumberFormat("id-ID").format(num);

  const fee = order.total * 0.05;
  const net = order.total - fee;

  // ===== HEADER =====
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(role === "buyer" ? "INVOICE" : "EARNINGS REPORT", 14, 20);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  // Right side info
  doc.text(`Invoice ID: ${order.invoice}`, 140, 20);
  doc.text(
    `Date: ${new Date(order.created_at).toLocaleDateString("en-GB", {
  day: "2-digit",
  month: "short",
  year: "numeric",
})}`,
    140,
    26
  );

  // ===== CUSTOMER / BUYER =====
  doc.setFont("helvetica", "bold");
  doc.text(role === "buyer" ? "Bill To:" : "Buyer:", 14, 35);

  doc.setFont("helvetica", "normal");
  doc.text(order.user.name, 14, 41);

  // ===== LINE SEPARATOR =====
  doc.setDrawColor(200);
  doc.line(14, 45, 196, 45);

  // ===== TABLE HEADER =====
  doc.setFont("helvetica", "bold");
  doc.text("Product", 14, 55);
  doc.text("Qty", 120, 55);
  doc.text("Price", 160, 55, { align: "right" });

  doc.line(14, 58, 196, 58);

  // ===== TABLE ROW =====
  doc.setFont("helvetica", "normal");
  doc.text(order.product.title, 14, 65);
  doc.text(String(order.qty), 120, 65);
  doc.text(`Rp ${formatRupiah(order.total)}`, 196, 65, { align: "right" });

  // ===== TOTAL BOX =====
  let startY = 80;

  doc.setDrawColor(220);
  doc.rect(120, startY, 76, role === "buyer" ? 20 : 35);

  doc.setFont("helvetica", "normal");

  if (role === "buyer") {
    doc.text("Total Paid", 122, startY + 8);
    doc.text(
      `Rp ${formatRupiah(order.total)}`,
      194,
      startY + 8,
      { align: "right" }
    );
  } else {
    doc.text("Subtotal", 122, startY + 8);
    doc.text(
      `Rp ${formatRupiah(order.total)}`,
      194,
      startY + 8,
      { align: "right" }
    );

    doc.text("Platform Fee (5%)", 122, startY + 16);
    doc.text(`Rp ${formatRupiah(fee)}`, 194, startY + 16, {
      align: "right",
    });

    doc.setFont("helvetica", "bold");
    doc.text("Net Earning", 122, startY + 26);
    doc.text(`Rp ${formatRupiah(net)}`, 194, startY + 26, {
      align: "right",
    });
  }

  // ===== FOOTER =====
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  doc.text(
    role === "buyer"
      ? "Thank you for your purchase!"
      : "This is your earnings summary from this order.",
    14,
    130
  );

  doc.text("Generated by SubGame Platform", 14, 136);

  // ===== DOWNLOAD =====
  doc.save(`${role}-invoice-${order.invoice}.pdf`);
};